# Generated by Django 4.2.3 on 2023-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='pontos',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
